name: flutter_application_1
description: "A new Flutter project for medical appointment management."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.18.0 # Para formato de fechas y horas
  cupertino_icons: ^1.0.8
  sqflite: ^2.2.8  # Para usar SQLite
  path: ^1.8.3     # Manejo de rutas para SQLite
  provider: ^6.1.2 # Gestión de estado para la app

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0 # Linting para buenas prácticas

flutter:
  uses-material-design: true
